openapi: 3.0.0
info:
  title: YouTube Like
  description: |-
    Aplikasi sederhana yang terinspirasi dari YouTube
  contact:
    email: itsme@tatang.dev
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Test local computer
  - url: https://test.youtube-like.com
    description: Staging
  - url: https://youtube-like.com
    description: Production
tags:
  - name: Auth
    description: Proses Autentikasi
  - name: Channels
    description: Channel Data
paths:
  /register:
    post:
      tags:
        - Auth
      summary: Mendaftarkan User Baru
      description: Mendaftarkan User Baru (desc)
      operationId: post-register-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: sabrina
                email:
                  type: string
                  example: sabrina@mail.com
                password:
                  type: string
                  example: password123
      responses:
        "201":
          description: Success Register
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success
                  data: 
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: sabrina
                      email:
                        type: string
                        example: sabrina@mail.com
        "400":
          description: Error from user
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: boolean
                        example: false
                      message:
                        type: string
                        example: email already used!
                      data: 
                        type: object
                  - type: object
                    properties:
                      status:
                        type: boolean
                        example: false
                      message:
                        type: string
                        example: name, email and password is required!
                      data: 
                        type: object
              examples:
                duplicated-email:
                  summary: If email already used
                  value:
                    status: false
                    message: email already used!
                    data: {}
                bad-request:
                  summary: If required data is not provided
                  value:
                    status: false
                    message: name, email and password is required!
                    data: {}
                    
  /login:
    post:
      tags:
        - Auth
      summary: Mendapatkan token
      description: Mendapatkan token (desc)
      operationId: post-login-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: sabrina@mail.com
                password:
                  type: string
                  example: password123
      responses:
        "200":
          description: Success Login
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success
                  data: 
                    type: object
                    properties:
                      token:
                        type: string
        "400":
          description: Error from user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: email or password is invalid!
                  data: 
                    type: object
  /whoami:
    get:
      tags:
        - Auth
      summary: Mendapatkan info user
      description: Mendapatkan info user (desc)
      operationId: get-whoami
      responses:
        "200":
          description: Success Validated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success
                  data: 
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: sabrina
                          email:
                            type: string
                            example: sabrina@mail.com
      security:
        - jwt_token: []
  /channels/{id}:
    put:
      tags:
        - Channels
      summary: Update channel data
      description: Update channel data (desc)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: id of channel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Close The Door
                description:
                  type: string
                  example: Podcast minta maaf
      responses:
        "200":
          description: Success Validated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success
                  data: 
                    type: integer
                    example: 1
      security:
        - jwt_token: []
  /channels:
    post:
      tags:
        - Channels
      summary: Mendaftarkan Channel Baru
      description: Mendaftarkan Channel Baru (desc)
      operationId: post-register-Channel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                name:
                  type: string
                  example: Deddy Corbuzier
                description:
                  type: string
                  example: Podcast Minta Maaf
      responses:
        "201":
          description: Success Create Channel
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success
                  data: 
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Deddy Corbuzier
                      description:
                        type: string
                        example: Podcast Minta Maaf
      security:
        - jwt_token: []
  
    get:
      tags:
        - Channels
      summary: Get All Data Channel
      description: Get All Data Channel (desc)
      operationId: get-data-Channel
      responses:
        "200":
          description: Menampilkan Semua Data Channel
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success
                  data: 
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Deddy Corbuzier
                      description:
                        type: string
                        example: Podcast Minta Maaf
      security:
        - jwt_token: []
     
    
components:
  securitySchemes:
    jwt_token:
      type: apiKey
      in: header
      name: token